-- Owner-scoped local chat history for the Warehouse Operations assistant.
-- IDs are generated by the application; no database UUID defaults or
-- sequences are used. Apply this migration before agent-change-sets and
-- agent-spreadsheet.
BEGIN;

CREATE TABLE logo.agent_chat_session (
    id                    uuid        PRIMARY KEY,
    user_login            text        NOT NULL,
    title                 text        NOT NULL DEFAULT '',
    active_turn_id        uuid,
    turn_lease_expires_at timestamptz,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    expires_at            timestamptz NOT NULL,
    UNIQUE (id, user_login)
);

CREATE INDEX agent_chat_session_owner_updated_idx
    ON logo.agent_chat_session (user_login, updated_at DESC);

CREATE TABLE logo.agent_chat_message (
    id           uuid        PRIMARY KEY,
    session_id   uuid        NOT NULL,
    user_login   text        NOT NULL,
    turn_id      uuid        NOT NULL,
    role         text        NOT NULL
                 CHECK (role IN ('user', 'assistant')),
    status       text        NOT NULL
                 CHECK (status IN ('complete', 'failed', 'cancelled')),
    content      text        NOT NULL DEFAULT '',
    replay_items jsonb       NOT NULL DEFAULT '[]'::jsonb
                 CHECK (jsonb_typeof(replay_items) = 'array'),
    created_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (session_id, turn_id, role),
    FOREIGN KEY (session_id, user_login)
        REFERENCES logo.agent_chat_session (id, user_login)
        ON DELETE CASCADE
);

CREATE INDEX agent_chat_message_owner_session_idx
    ON logo.agent_chat_message (
        user_login, session_id, created_at DESC, id DESC
    );

GRANT SELECT, INSERT, UPDATE, DELETE
    ON logo.agent_chat_session, logo.agent_chat_message
    TO logo_admin;

COMMIT;
