-- Seed woo.store_blog_map.blog_name from PROD WordPress site titles (2026-09-03).
-- Regenerate: on prod `wp eval` over get_sites() printing blog_id + blogname, then
-- one UPDATE per blog (see logo-admin/README.md, "Store display names").
BEGIN;
UPDATE woo.store_blog_map SET blog_name = 'Arborwear' WHERE blog_id = 1;
UPDATE woo.store_blog_map SET blog_name = 'Payne Tompkins' WHERE blog_id = 3;
UPDATE woo.store_blog_map SET blog_name = 'Conservation Legacy' WHERE blog_id = 4;
UPDATE woo.store_blog_map SET blog_name = 'Cleveland Metroparks' WHERE blog_id = 5;
UPDATE woo.store_blog_map SET blog_name = 'Independence Excavating' WHERE blog_id = 6;
UPDATE woo.store_blog_map SET blog_name = 'ISA' WHERE blog_id = 7;
UPDATE woo.store_blog_map SET blog_name = 'Nelson Tree' WHERE blog_id = 9;
UPDATE woo.store_blog_map SET blog_name = 'Progressive' WHERE blog_id = 10;
UPDATE woo.store_blog_map SET blog_name = 'SavATree' WHERE blog_id = 11;
UPDATE woo.store_blog_map SET blog_name = 'Townsend' WHERE blog_id = 13;
UPDATE woo.store_blog_map SET blog_name = 'WTS Management' WHERE blog_id = 14;
UPDATE woo.store_blog_map SET blog_name = 'ACRT' WHERE blog_id = 15;
UPDATE woo.store_blog_map SET blog_name = 'AMS' WHERE blog_id = 16;
UPDATE woo.store_blog_map SET blog_name = 'Lake Farmparks' WHERE blog_id = 17;
UPDATE woo.store_blog_map SET blog_name = 'Lake Metroparks Natural Resources' WHERE blog_id = 18;
UPDATE woo.store_blog_map SET blog_name = 'Lake Metroparks Outdoor Connections' WHERE blog_id = 19;
UPDATE woo.store_blog_map SET blog_name = 'Lake Metroparks Planning Division' WHERE blog_id = 20;
UPDATE woo.store_blog_map SET blog_name = 'Monster Tree' WHERE blog_id = 22;
UPDATE woo.store_blog_map SET blog_name = 'Penn Line' WHERE blog_id = 23;
UPDATE woo.store_blog_map SET blog_name = 'Wachtel Tree Science' WHERE blog_id = 24;
UPDATE woo.store_blog_map SET blog_name = 'O''Connell Electric' WHERE blog_id = 25;
UPDATE woo.store_blog_map SET blog_name = 'Mainscape' WHERE blog_id = 29;
UPDATE woo.store_blog_map SET blog_name = 'Ryan Lawn' WHERE blog_id = 30;
UPDATE woo.store_blog_map SET blog_name = 'Town of Parker' WHERE blog_id = 31;
UPDATE woo.store_blog_map SET blog_name = 'Bartlett Company Apparel' WHERE blog_id = 32;
UPDATE woo.store_blog_map SET blog_name = 'Lucas Tree' WHERE blog_id = 33;
UPDATE woo.store_blog_map SET blog_name = 'Asplundh' WHERE blog_id = 34;
UPDATE woo.store_blog_map SET blog_name = 'brookeshenderson' WHERE blog_id = 36;
UPDATE woo.store_blog_map SET blog_name = 'BrightView' WHERE blog_id = 37;
UPDATE woo.store_blog_map SET blog_name = 'SavATree Arborists & Management-Arborwear' WHERE blog_id = 39;
UPDATE woo.store_blog_map SET blog_name = 'SavATree Employee Equipment Account' WHERE blog_id = 40;
UPDATE woo.store_blog_map SET blog_name = 'SCA' WHERE blog_id = 41;
UPDATE woo.store_blog_map SET blog_name = 'SCA Staff Web Store' WHERE blog_id = 42;
UPDATE woo.store_blog_map SET blog_name = 'WTS Crew' WHERE blog_id = 43;
UPDATE woo.store_blog_map SET blog_name = 'Arbor Masters Tree Service' WHERE blog_id = 45;
UPDATE woo.store_blog_map SET blog_name = 'Demo Webstore' WHERE blog_id = 46;
UPDATE woo.store_blog_map SET blog_name = 'Davey Canada' WHERE blog_id = 47;
UPDATE woo.store_blog_map SET blog_name = 'Tri-State Bobcat' WHERE blog_id = 48;
UPDATE woo.store_blog_map SET blog_name = 'Xylem Tree Experts' WHERE blog_id = 49;
UPDATE woo.store_blog_map SET blog_name = 'Cumberland Valley Tree' WHERE blog_id = 50;
UPDATE woo.store_blog_map SET blog_name = 'ArborWorks' WHERE blog_id = 51;
UPDATE woo.store_blog_map SET blog_name = 'Rainbow Tree' WHERE blog_id = 52;
UPDATE woo.store_blog_map SET blog_name = 'Utility Arborist Association' WHERE blog_id = 54;
UPDATE woo.store_blog_map SET blog_name = 'Saluting Branches' WHERE blog_id = 55;
UPDATE woo.store_blog_map SET blog_name = 'Wright SET' WHERE blog_id = 56;
UPDATE woo.store_blog_map SET blog_name = 'Summit Landscape Management' WHERE blog_id = 57;
UPDATE woo.store_blog_map SET blog_name = 'Lewis Tree' WHERE blog_id = 58;
UPDATE woo.store_blog_map SET blog_name = 'Square' WHERE blog_id = 59;
UPDATE woo.store_blog_map SET blog_name = 'Kendall Vegetation Management' WHERE blog_id = 61;
UPDATE woo.store_blog_map SET blog_name = 'Aerial Solutions' WHERE blog_id = 62;
UPDATE woo.store_blog_map SET blog_name = 'Stewards' WHERE blog_id = 63;
UPDATE woo.store_blog_map SET blog_name = 'Mariani' WHERE blog_id = 64;
UPDATE woo.store_blog_map SET blog_name = 'EDM' WHERE blog_id = 65;
UPDATE woo.store_blog_map SET blog_name = 'Byrider' WHERE blog_id = 66;
UPDATE woo.store_blog_map SET blog_name = 'Davey Commercial' WHERE blog_id = 68;
UPDATE woo.store_blog_map SET blog_name = 'Davey Residential' WHERE blog_id = 69;
UPDATE woo.store_blog_map SET blog_name = 'Tree Care of New York' WHERE blog_id = 70;
UPDATE woo.store_blog_map SET blog_name = 'Decco Approved' WHERE blog_id = 71;
UPDATE woo.store_blog_map SET blog_name = 'Monarch Tree' WHERE blog_id = 73;
UPDATE woo.store_blog_map SET blog_name = 'XKIG' WHERE blog_id = 74;
UPDATE woo.store_blog_map SET blog_name = 'GIP' WHERE blog_id = 75;
UPDATE woo.store_blog_map SET blog_name = 'Ironwood' WHERE blog_id = 79;
UPDATE woo.store_blog_map SET blog_name = 'Marine Solutions' WHERE blog_id = 82;
UPDATE woo.store_blog_map SET blog_name = 'Treeways' WHERE blog_id = 83;
UPDATE woo.store_blog_map SET blog_name = 'Northern Zielies' WHERE blog_id = 84;
UPDATE woo.store_blog_map SET blog_name = 'Brightview Tree Care' WHERE blog_id = 85;
UPDATE woo.store_blog_map SET blog_name = 'Davey Award' WHERE blog_id = 87;
UPDATE woo.store_blog_map SET blog_name = 'State College Borough' WHERE blog_id = 89;
UPDATE woo.store_blog_map SET blog_name = 'Maverick Envrionmental' WHERE blog_id = 91;
UPDATE woo.store_blog_map SET blog_name = 'Xylem Tree Care' WHERE blog_id = 92;
UPDATE woo.store_blog_map SET blog_name = 'Joshua Tree' WHERE blog_id = 93;
UPDATE woo.store_blog_map SET blog_name = 'Stanley Tree' WHERE blog_id = 95;
UPDATE woo.store_blog_map SET blog_name = 'Davey RC Safety' WHERE blog_id = 96;
UPDATE woo.store_blog_map SET blog_name = 'Moorhead Brothers' WHERE blog_id = 97;
UPDATE woo.store_blog_map SET blog_name = 'Southview' WHERE blog_id = 98;
UPDATE woo.store_blog_map SET blog_name = 'Thrive' WHERE blog_id = 100;
COMMIT;
